title: "Mohammad Abdullah, PMP® CFPS®"
email: ""
description: >- 
  Highly experienced Sales Manager / Certified Fire Protection Specialist (CFPS)
  | Industrial Automation & Energy | Low Current | Fire Protection
baseurl: "" 
url: "https://m-o-abdullah.github.io"
theme: minima
